---
title: "Crimtab Data : Tests of Normality"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include = FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
options(width = 180)
```

## Data Loading

```{r, data}
load("./crimtab.RData")
str(crimtab_long_df)
```

Quetelet의 가슴둘레 자료에서 살핀 바와 같이 이 자료를 그대로 ad.test 등에 적용하면 매우 작은 p-value 가 예상됨.

```{r, Anderson-Darling test}
# install.packages("nortest", repos = "https://cran.rstudio.com")
library(nortest)
# ad.test(crimtab_long_df[, 1])
# ad.test(crimtab_long_df[, 2])
kable(sapply(crimtab_long_df, FUN = ad.test))
```

<P style = "page-break-before:always">

## Random Noise

`height`의 경우 인치 단위로 측정한 자료임. 이 점에 유의하여 원 자료의 모습에 가깝게 noise 를 넣기 위하여 생성

```{r, histogram of noise}
set.seed(1)
r_noise <- runif(3000) - 0.5
hist(r_noise, 
     prob = TRUE, 
     xlim = c(-0.5, 0.5), 
     ylim = c(0, 1.5))
```

<P style = "page-break-before:always">

## Plots

noise를 넣어 Histogram 과 QQnorm 작성

### finger with noise

#### Histogram

```{r, fig.width = 8, fig.height = 6}
crimtab_long_df_noise <- crimtab_long_df
crimtab_long_df_noise[, "finger"] <- 
        crimtab_long_df[, "finger"] + r_noise/10
hist(crimtab_long_df_noise[, "finger"], 
     prob = TRUE, 
     nclass = 42)
```

<P style = "page-break-before:always">

#### QQnorm

```{r, fig.width = 12, fig.height = 6}
par(mfrow = c(1, 2))
qqnorm(crimtab_long_df[, "finger"])
qqnorm(crimtab_long_df_noise[, "finger"])
par(mfrow = c(1, 1))
```

<P style = "page-break-before:always">

### Height with noise

#### Histogram

```{r, fig.width = 8, fig.height = 6}
crimtab_long_df_noise[, "height"] <- 
        crimtab_long_df[, "height"] + r_noise
hist(crimtab_long_df_noise[, "height"], 
     prob = TRUE, 
     nclass = 22)
```

<P style = "page-break-before:always">

#### QQnorm

```{r, fig.width = 12, fig.height = 6}
par(mfrow = c(1, 2))
qqnorm(crimtab_long_df[, "height"])
qqnorm(crimtab_long_df_noise[, "height"])
par(mfrow = c(1, 1))
```

<P style = "page-break-before:always">

### Tests of Normality

```{r}
kable(sapply(crimtab_long_df_noise, ad.test))
kable(sapply(crimtab_long_df_noise, cvm.test))
kable(sapply(crimtab_long_df_noise, lillie.test))
# ad.test(crimtab_long_df[, 2] + r_noise)
# cvm.test(crimtab_long_df[, 2] + r_noise)
# lillie.test(crimtab.long[,2]+r_noise)
# ad.test(crimtab.long[, 1] + r_noise/10)
# cvm.test(crimtab.long[, 1] + r_noise/10)
# lillie.test(crimtab.long[, 1] + r_noise/10)
```

```{r, save}
save.image("./crimtab_noise.RData")
```