---
title: "Online Quiz 191008 Submission Time"
# author: "coop711"
# date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("pander", repos = "https://cran.rstudio.com")
# install.packages("xlsx", repos = "https://cran.rstudio.com")
# install.packages("readr", repos = "https://cran/rstudio.com")
library(xlsx)
library(pander)
library(knitr)
library(readr)
library(magrittr)
panderOptions('table.split.table', Inf)
options(width = 180)
```

<!--
### Data
-->

```{r, data, echo = FALSE, results = "hide"}
load("./red_and_black_190923_data.RData")
quiz10 <- read.xlsx("../data/etest191008.xlsx", 
                        sheetIndex = 1, 
                        startRow = 3, 
                        endRow = 161, 
                        colIndex = 2:7, 
#                        colClasses = rep("character", 6), 
                        encoding = "UTF-8",
                        stringsAsFactors = FALSE)
names(quiz10) <- c("name", "id", "dept", "score1", "score2", "time")
quiz10$group <- class_roll$group[match(quiz10$id, class_roll$id)]
quiz10$submit <- ifelse(is.na(quiz10$time), "미제출", "제출")
quiz10$hours_passed <- as.numeric(difftime(Sys.time(), quiz10$time, units = 'days'))
## 학교 정보시스템이 GMT로 표기되어 있어서 9시간의 타임갭을 감안하여야 함.
quiz10$days <- as.numeric(difftime("2019-10-09 09:00:00", quiz10$time, units = 'days'))
quiz10$hours <- as.numeric(difftime("2019-10-09 09:00:00", quiz10$time, units = 'hours'))
quiz10$bird <- factor(ifelse(quiz10$hours >= 48, "Early", "Late"), 
                      labels = c("48시간 이내 제출", "48시간 이후 제출"))
str(quiz10)
```


### 제출/미제출

제출시간이 기록되지 않은 사람은 미제출.

```{r, echo = FALSE, results = "markup"}
table(quiz10$group, quiz10$submit) %>%
 kable
chisq.test(table(quiz10$group, quiz10$submit)) %>%
  pander
```

## 제출 시간의 분포

마감 시간으로부터 얼마나 일찍 제출하는지 일 단위와 시간 단위로 측정하여 살펴보았다. 

### 시간 단위 기초통계량

```{r, echo = FALSE}
# quiz10$hours
summary(quiz10$hours)
stem(quiz10$hours)
max(quiz10$hours, na.rm = TRUE)
```

### 일 단위 마감 시간으로부터 제출 시간의 분포

```{r, echo = FALSE}
par(family = "")
table(cut(quiz10$days, breaks = c(0:7), include.lowest = TRUE)) %>%
  t %>%
  kable
barplot(rev(table(cut(quiz10$days, breaks = c(0:7), include.lowest = TRUE))), 
        space = 0,
        names.arg = c("수", "목", "금", "토","일","월", "화"))
title(main = "일 단위 퀴즈 제출 횟수")
```

### 시간 단위 마감 시간으로부터 제출 시간의 분포

```{r, echo = FALSE}
breaks <- c(seq(0, 48, by = 24), 49:54, seq(72, 168, by = 24))
breaks2 <- c(seq(0, 48, by = 24), 49:58, seq(72, 168, by = 24))
breaks3 <- c(0:6, 24:30, 48:54, seq(72, 144, by = 24), 145:150, 168)
breaks4 <- c(0:6, 24, 48:58, seq(72, 144, by = 24), 157:159, 168)
breaks5 <- c(0:12, 24, 25:40, seq(48, 144, by = 24), 157:159, 168)
table(cut(quiz10$hours, breaks = breaks4, include.lowest = TRUE)) %>%
  t %>%
  kable
```

### 시간 당 제출 건수의 분포

```{r, echo = FALSE}
par(family = "")
# widths <- c(rep(24, 4), 16, rep(1, 10), rep(24, 1), 14, rep(1, 10))
widths <- rev(diff(breaks))
# widths2 <- c(rep(24, 4), 16, rep(1, 10), rep(24, 2))
widths2 <- rev(diff(breaks2))
# widths3 <- c(18, rep(1, 6), rep(24, 3), 18, rep(1, 6),  18, rep(1, 6), 18, rep(1, 6))
widths3 <- rev(diff(breaks3))
# widths4 <- c(9, rep(1, 2), 13, rep(24, 3), 14, rep(1, 10),  24, 18, rep(1, 6))
widths4 <- rev(diff(breaks4))
widths5 <- rev(diff(breaks5))
# freqs <- table(cut(quiz10$hours, breaks = breaks2, include.lowest = TRUE))
freqs2 <- table(cut(quiz10$hours, breaks = breaks2, include.lowest = TRUE))
freqs3 <- table(cut(quiz10$hours, breaks = breaks3, include.lowest = TRUE))
freqs4 <- table(cut(quiz10$hours, breaks = breaks4, include.lowest = TRUE))
freqs5 <- table(cut(quiz10$hours, breaks = breaks5, include.lowest = TRUE))
# heights <- freqs / diff(breaks)
heights2 <- freqs2 / diff(breaks2)
heights3 <- freqs3 / diff(breaks3)
heights4 <- freqs4 / diff(breaks4)
heights5 <- freqs5 / diff(breaks5)
# names_args <- c("수", "목", "금", "토", "일", rep("", 10), "월", "화", rep("", 10))
names_args2 <- c("수", "목", "금", "토", "일", rep("", 10), "월", "화")
names_args3 <- c("수", rep("", 6),"목", "금", "토", "일", rep("", 6), "월", rep("", 6), "화", rep("", 6))
names_args4 <- c("수", rep("", 3),"목", "금", "토", "일", rep("", 10), "월", "화", rep("", 6))
names_args5 <- c("수", rep("", 3),"목", "금", "토", "일", "월", rep("", 16), "화", rep("", 12))
# barplot(height = rev(heights), width = widths, 
#         space = 0,
#         names.arg = names_args)
barplot(height = rev(heights4), width = widths4, 
        space = 0,
        names.arg = names_args4)
# barplot(height = rev(heights3), width = widths3, 
#         space = 0,
#         names.arg = names_args3)
title(main = "시간당 퀴즈 제출 분포")
arrows(x0 = 0, y0 = 3.2, x1 = 7, y1 = 0.6, length = 0.16, code = 2, col = "red", lwd = 1.5)
text(x = 5, y = 4, labels = "오전10시", srt = 16, col = "red")
arrows(x0 = 102, y0 = 3.6, x1 = 110, y1 = 0.8, length = 0.16, code = 2, col = "red", lwd = 1.5)
text(x = 102, y = 4, labels = "오후 6시", srt = 16, col = "red")
# arrows(x0 = 128, y0 = 3.6, x1 = 136, y1 = 1.2, length = 0.16, code = 2, col = "red", lwd = 1.5)
# text(x = 125, y = 4, labels = "오후 6시", srt = 16, col = "red")
arrows(x0 = 152, y0 = 3.6, x1 = 159, y1 = 0.8, length = 0.16, code = 2, col = "red", lwd = 1.5)
text(x = 153, y = 4, labels = "오후 6시", srt = 16, col = "red")
```

### 급히 제출한 사람과 일찍 낸 사람 비교

마감 3일 전 일요일 오후 6시 이후에 제출한 사람과 그 이전에 제출한 사람들의 특성 비교

#### 랜덤화 효과

```{r, echo = FALSE}
table(quiz10$group, quiz10$bird) %>%
  kable
chisq.test(table(quiz10$group, quiz10$bird)) %>%
  pander
```

#### 기초통계 비교

```{r, echo = FALSE}
pander(tapply(quiz10$score1, quiz10$bird, summary))
```

#### Box Plot

```{r, echo = FALSE}
par(family = "")
plot(score1 ~ bird, data = quiz10, 
     main = "마감 2일 전 0시부터 제출한 사람과 그 전에 낸 사람", 
     xlab = "제출 시점", ylab = "퀴즈 점수")
```

#### t test

```{r, echo = FALSE}
t.test(score1 ~ bird, data = quiz10)
# %>% pander
```

### quiz09 와 quiz10

```{r, echo = FALSE}
quiz09 <- readRDS("quiz09.RDs")
```

#### 일요일에 제출한 사람들

##### quiz09

```{r, echo = FALSE}
quiz09$id[quiz09$days >= 0 & quiz09$days <= 1] %>%
  is.na %>%
  `!` %>%
  sum 
```
##### quiz10

```{r, echo = FALSE}
quiz10$id[quiz10$days >= 2 & quiz10$days <= 3] %>%
  is.na %>%
  `!` %>%
  sum 
```

#### 두 퀴즈를 일요일에 제출한 사람들

```{r, echo = FALSE}
intersect(quiz09$id[quiz09$days >= 0 & quiz09$days <= 1], quiz10$id[quiz10$days >= 2 & quiz10$days <= 3]) %>% 
  is.na %>%
  `!` %>%
  sum
```

#### 수요일에 제출한 사람들

##### quiz09

```{r, echo = FALSE}
quiz09$id[quiz09$days >= 4 & quiz09$days <= 5] %>%
  is.na %>%
  `!` %>%
  sum 
```

##### quiz10

```{r, echo = FALSE}
quiz10$id[quiz10$days >= 6 & quiz10$days <= 7] %>%
  is.na %>%
  `!` %>%
  sum 
```

#### 두 퀴즈를 수요일에 제출한 사람들

```{r, echo = FALSE}
intersect(quiz09$id[quiz09$days >= 4 & quiz09$days <= 5], quiz10$id[quiz10$days >= 6 & quiz10$days <= 7]) %>% length
```

## Save

```{r, echo = FALSE}
saveRDS(quiz10, file = "quiz10.RDs")
```