---
title: "Quiz01 Submission Time"
# author: "coop711"
# date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("pander", repos = "https://cran.rstudio.com")
# install.packages("xlsx", repos = "https://cran.rstudio.com")
library(xlsx)
library(pander)
library(knitr)
library(magrittr)
library(extrafont)
panderOptions('table.split.table', Inf)
options(width = 180)
```

<!--
### Data
-->

```{r, data, echo = FALSE, results = "hide"}
class_id_group0901 <- readRDS("./class_id_group180901.RDS")
id0901 <- class_id_group0901$id
class_id_group0907 <- readRDS("./class_id_group180907.RDS")
id0907 <- class_id_group0907$id
id_new <- setdiff(id0907, id0901)
quiz01 <- read.xlsx("../data/etest01.xlsx", 
                        sheetIndex = 1, 
                        startRow = 3, 
                        endRow = 159, 
                        colIndex = 2:5, 
#                        colClasses = rep("character", 6), 
                        encoding = "UTF-8",
                        stringsAsFactors = FALSE)
names(quiz01) <- c("id", "score1", "score2", "time")
quiz01$group <- class_id_group0907$group[match(quiz01$id, id0907)]
quiz01$submit <- ifelse(is.na(quiz01$time), "미제출", "제출")
quiz01$hours_passed <- as.numeric(difftime(Sys.time(), quiz01$time, units = 'days'))
## 학교 정보시스템이 GMT로 표기되어 있어서 9시간의 타임갭을 감안하여야 함.
quiz01$days <- as.numeric(difftime("2018-09-10 09:00:00", quiz01$time, units = 'days'))
quiz01$hours <- as.numeric(difftime("2018-09-10 09:00:00", quiz01$time, units = 'hours'))
quiz01$bird <- factor(ifelse(quiz01$hours >= 6, "Early", "Late"), 
                      labels = c("마감날 오후6시 이전 제출", "마감날 오후6시 이후 제출"))
quiz01$new <- factor(ifelse(quiz01$id %in% id_new, "new", "stay"), labels = c("변경", "고수"))
str(quiz01)
```
### 제출 시간

```{r, echo = FALSE}
pander(head(quiz01[, c("score1", "time")], n = 10))
```

### 제출/미제출

제출시간이 기록되지 않은 사람은 미제출.

```{r, echo = FALSE, results = "markup"}
kable(table(quiz01$group, quiz01$submit))
```

### 수강변경 여부와 제출/미제출

수강변경으로 들어온 사람들의 미제출이 더 많은 것으로 관찰되나 통계적으로 유의한 수준은 아님.

```{r, echo = FALSE}
quiz01$new %>%
  table(quiz01$submit) %>%
  cbind(., "계" = rowSums(.)) %>%
  kable
quiz01$new %>%
  table(quiz01$submit) %>%
  chisq.test %>%
  pander
quiz01$new %>%
  table(quiz01$submit) %>%
  prop.table(margin = 1) %>%
  `*`(100) %>%
  cbind(., "계" = rowSums(.)) %>%
  format(digits = 1, nsmall = 1) %>%
  kable
```

## 제출 시간의 분포

마감 시간으로부터 얼마나 일찍 제출하는지 일 단위와 시간 단위로 측정하여 살펴보았다. 

### 시간 단위 기초통계량

```{r, echo = FALSE}
# quiz01$hours
summary(quiz01$hours)
stem(quiz01$hours)
max(quiz01$hours, na.rm = TRUE)
```

### 일 단위 마감 시간으로부터 제출 시간의 분포

```{r, echo = FALSE}
par(family = "Malgun Gothic")
pander(table(cut(quiz01$days, breaks = c(0:7), 
                 include.lowest = TRUE)), caption = "일 단위")
barplot(rev(table(cut(quiz01$days, breaks = c(0:7), include.lowest = TRUE))), 
        space = 0,
        names.arg = paste0(7:1, "일"))
title(main = "일 단위 퀴즈 제출 횟수")
```

### 시간 단위 마감 시간으로부터 제출 시간의 분포

```{r, echo = FALSE}
breaks <- c(0:6, seq(24, 168, by = 24))
pander(table(cut(quiz01$hours, breaks = breaks, include.lowest = TRUE)), caption = "시간 단위")
```

### 시간 당 제출 건수의 분포

```{r, echo = FALSE}
par(family = "Malgun Gothic")
widths <- c(rep(24, 6), 18, rep(1, 6))
freqs <- table(cut(quiz01$hours, breaks = c(0:6, seq(24, 168, by = 24)), include.lowest = TRUE))
heights <- freqs / diff(breaks)
names_args <- c(paste0(7:1, "일"), rep("", 6))
barplot(height = rev(heights), width = widths, 
        space = 0,
        names.arg = names_args)
title(main = "시간당 퀴즈 제출 분포")
arrows(x0 = 144, y0 = 4, x1 = 160, y1 = 1, length = 0.15, code = 2, col = "red", lwd = 1.5)
text(x = 139, y = 4.5, labels = "저녁 6시", srt = 30, col = "red")
```

### 급히 제출한 사람과 일찍 낸 사람 비교

마감 당일 오후 2시 이후에 제출한 사람과 그 이전에 제출한 사람들의 특성 비교

#### 랜덤화 효과

```{r, echo = FALSE}
kable(table(quiz01$group, quiz01$bird))
```

#### 기초통계 비교

```{r, echo = FALSE}
pander(tapply(quiz01$score1, quiz01$bird, summary))
```

#### Box Plot

```{r, echo = FALSE}
par(family = "Malgun Gothic")
plot(score1 ~ bird, data = quiz01, 
     main = "급히 낸 사람과 일찍 낸 사람", 
     xlab = "제출 시점", ylab = "퀴즈 점수")
```

#### t test

```{r, echo = FALSE}
t.test(score1 ~ bird, data = quiz01)
# pander(t.test(score1 ~ bird, data = quiz01))
```
