---
title: "Quiz04 Submission Time"
# author: "coop711"
# date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("pander", repos = "https://cran.rstudio.com")
# install.packages("xlsx", repos = "https://cran.rstudio.com")
# install.packages("readr", repos = "https://cran/rstudio.com")
library(xlsx)
library(pander)
library(knitr)
library(extrafont)
panderOptions('table.split.table', Inf)
options(width = 180)
```

<!--
### Data
-->

```{r, data, echo = FALSE, results = "hide"}
class_id_group0907 <- readRDS("./class_id_group180907.RDS")
quiz04 <- read.xlsx("../data/etest04.xlsx", 
                        sheetIndex = 1, 
                        startRow = 3, 
                        endRow = 159, 
                        colIndex = 2:5, 
#                        colClasses = rep("character", 6), 
                        encoding = "UTF-8",
                        stringsAsFactors = FALSE)
names(quiz04) <- c("id", "score1", "score2", "time")
quiz04$group <- class_id_group0907$group[match(quiz04$id, class_id_group0907$id)]
quiz04$submit <- ifelse(is.na(quiz04$time), "미제출", "제출")
quiz04$hours_passed <- as.numeric(difftime(Sys.time(), quiz04$time, units = 'days'))
## 학교 정보시스템이 GMT로 표기되어 있어서 9시간의 타임갭을 감안하여야 함.
quiz04$days <- as.numeric(difftime("2018-09-27 09:00:00", quiz04$time, units = 'days'))
quiz04$hours <- as.numeric(difftime("2018-09-27 09:00:00", quiz04$time, units = 'hours'))
quiz04$bird <- factor(ifelse(quiz04$hours >= 34, "Early", "Late"), 
                      labels = c("당초 마감날 오후2시 이전 제출", "당초 마감날 오후2시 이후 제출"))
str(quiz04)
```


### 제출/미제출

제출시간이 기록되지 않은 사람은 미제출.

```{r, echo = FALSE, results = "markup"}
kable(table(quiz04$group, quiz04$submit))
pander(chisq.test(table(quiz04$group, quiz04$submit)))
```

## 제출 시간의 분포

마감 시간으로부터 얼마나 일찍 제출하는지 일 단위와 시간 단위로 측정하여 살펴보았다. 

### 시간 단위 기초통계량

```{r, echo = FALSE}
# quiz04$hours
summary(quiz04$hours)
stem(quiz04$hours)
max(quiz04$hours, na.rm = TRUE)
```

### 일 단위 마감 시간으로부터 제출 시간의 분포

```{r, echo = FALSE}
par(family = "Malgun Gothic")
pander(table(cut(quiz04$days, breaks = c(0:8), include.lowest = TRUE)), caption = "일 단위")
barplot(rev(table(cut(quiz04$days, breaks = c(0:8), include.lowest = TRUE))), 
        space = 0,
        names.arg = paste0(c(7:1, -1), "일"))
title(main = "일 단위 퀴즈 제출 횟수")
```

### 오후 6시 이전/이후 단위 마감 시간으로부터 제출 시간의 분포

```{r, echo = FALSE}
breaks <- c(0, 6, 24, 30, 48, 54, 72, 78, 96, 102, 120, 126, 144, 150, 168, 174, 192)
# breaks <- c(0, 24, 25:34, seq(48, 192, by = 24))
pander(table(cut(quiz04$hours, breaks = breaks, include.lowest = TRUE)), caption = "시간 단위")
```

### 시간 당 제출 건수의 분포

```{r, echo = FALSE, fig.width = 12}
par(family = "Malgun Gothic")
widths <- c(rep(c(18, 6), times = 8))
freqs <- table(cut(quiz04$hours, breaks = breaks, include.lowest = TRUE))
heights <- freqs / diff(breaks)
names_args <- c(unlist(strsplit(paste(paste0("D-", 7:1), "6PM", sep = " "), split = " ")), "D+1", "6PM")
# names_args <- c("7일", "오후6시", "6일", "오후6시", "5일", "오후6시", "4일", "오후6시", "3일", "오후6시", "2일", "오후6시", "1일", "오후6시", "-1일", "오후6시")
barplot(height = rev(heights), width = widths, 
        space = 0,
        names.arg = names_args)
title(main = "시간당 퀴즈 제출 건수 분포")
# arrows(x0 = 144, y0 = 3, x1 = 156, y1 = 0.75, length = 0.15, code = 2, col = "red", lwd = 1.5)
# text(x = 141, y = 3.2, labels = "오후 2시", srt = 15, col = "red")
```

### 급히 제출한 사람과 일찍 낸 사람 비교

마감 당일 오후 2시 이후에 제출한 사람과 그 이전에 제출한 사람들의 특성 비교

#### 랜덤화 효과

```{r, echo = FALSE}
kable(table(quiz04$group, quiz04$bird))
pander(chisq.test(table(quiz04$group, quiz04$bird)))
```

#### 기초통계 비교

```{r, echo = FALSE}
pander(tapply(quiz04$score1, quiz04$bird, summary))
```

#### Box Plot

```{r, echo = FALSE}
par(family = "Malgun Gothic")
plot(score1 ~ bird, data = quiz04, 
     main = "급히 낸 사람과 일찍 낸 사람", 
     xlab = "제출 시점", ylab = "퀴즈 점수")
```

#### t test

```{r, echo = FALSE}
t.test(score1 ~ bird, data = quiz04)
```
