---
title: "Red and Black : Search for the Best"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(pander)
library(knitr)
library(magrittr)
panderOptions('table.split.table', Inf)
```

## Data

```{r, data, echo = TRUE, results = 'show'}
class_roll <- readRDS("./class_roll_masked_2402.RDS")
str(class_roll)
```

## `red_and_black()`

```{r, function, echo = TRUE}
red_and_black <-
function(k){
  set.seed(k)
  N <- nrow(class_roll) 
  class_roll$group <- 
    sample(1:N) %%
    2 %>%
    factor(levels = c(0, 1), labels = c("Red", "Black"))

## 학번
  class_roll$id_2 <-
    class_roll$id %>%
    substr(1, 4) %>%
    ifelse(as.numeric(.) <= 2018, "2018", .)
  X1 <- class_roll %$%
    table(.$group, .$id_2) %>%
    chisq.test(simulate.p.value = FALSE) %>%
    `[[`(1) %>%
    unname

## e-mail 서비스업체
  isp <- class_roll$email %>%
    strsplit("@", fixed = TRUE) %>%
    sapply("[", 2) %>%
    strsplit("[.]", fixed = FALSE) %>%
    sapply("[", 1)
  X2 <- isp %>%
    `%in%`(c("naver", "gmail")) %>%
    ifelse(isp, "기타서비스") %>%
    factor(levels = c("naver", "gmail", "기타서비스"),
           labels = c("네이버", "구글", "기타서비스")) %>%
    table(class_roll$group, .)  %>%
    chisq.test(simulate.p.value = FALSE) %>%
    `[[`(1) %>%
    unname

## 휴대폰번호의 분포
  cut_label <- paste(paste0(0:9, "000"), paste0(0:9, "999"), 
                     sep = "~")
  X3 <- class_roll$cell_no %>%
    substr(start = 8, stop = 11) %>%
    sapply(as.numeric) %>%
    cut(labels = cut_label, 
        breaks = seq(0, 10000, by = 1000)) %>%
    table(class_roll$group, .) %>%
    chisq.test(simulate.p.value = FALSE) %>%
    `[[`(1) %>%
    unname

## 성씨 분포
  f_name <- class_roll$name %>%
    substring(first = 1, last = 1) 
  X4 <- f_name %>%
    `%in%`(c("김", "이", "박", "최", "정")) %>%
    ifelse(f_name, "기타") %>%
    factor(levels = c("김", "이", "박", "최", "정", "기타")) %>%
    table(class_roll$group, .) %>%
    chisq.test(simulate.p.value = FALSE) %>%
    `[[`(1) %>%
    unname
  
## 단과대학
  X5 <- 
    class_roll %$%
    table(.$group, .$college) %>%
    chisq.test(simulate.p.value = FALSE) %>%
    `[[`(1) %>%
    unname

## Sum of Chi_Squares
  Xsum <- X1 + X2 + X3 + X4 + X5
  Xsum

## Results
#  list(Values = c(X1, X2, X3, X4, X5), Xsum = Xsum)
}
```

## Search for Best Configuration

```{r, echo = TRUE}
M1 <- 1
M2 <- 100
Xsum <- sapply(M1:M2, red_and_black)
names(Xsum) <- M1:M2
```

## Summary

```{r, summary, echo = TRUE}
Xsum %>%
  summary %>%
  round(2) 
Xsum %>%
  sd %>%
  round(2)
Xsum %>%
  `<=`(9) %>%
  which %>%
  `[`(Xsum, .) %>%
  round(2)
Xmin <- names(Xsum[which(Xsum == min(Xsum))])
Xmin
```

## Plot

```{r, echo = FALSE}
hist(Xsum, prob = TRUE, nclass = 30, xlim = c(0, 70), ylim = c(0, 0.06))
x <- seq(0, 70, by = 0.1)
lines(x, dchisq(x, df = 32), col = "red")
legend("topright", inset = 0.05, legend = c("Xsum", "Chi-square(32)"), col = c("black", "red"), lty = 1)
plot(density(Xsum), xlim = c(0, 70), ylim = c(0, 0.06), main = "Density Estimation of Xsum")
lines(x, dchisq(x, df = 32), col = "red")
legend("topright", inset = 0.05, legend = c("Xsum", "Chi-square(32)"), col = c("black", "red"), lty = 1)
```

## Randomization Report

```{r, randomization}
set.seed(Xmin)
N <- nrow(class_roll) 
class_roll$group <- 
  sample(1:N) %%
  2 %>%
  factor(levels = c(0, 1), labels = c("Red", "Black"))
red_and_black(Xmin)
```

## 학번

```{r, id, echo = TRUE, eval = TRUE}
class_roll$id_2 <-
  class_roll$id %>%
  substr(1, 4) %>%
  ifelse(. <= 2018, "2018", .)
tbl1 <- class_roll %$%
  table(.$group, .$id_2) %>%
  `colnames<-`(c("2018 이전", 2019:2024)) 
tbl1 %>%
  pander
X1min <- tbl1 %>%
  chisq.test(simulate.p.value = TRUE) %>%
  `[[`(1)
X1min
```

## e-mail 서비스업체

```{r, e_mail, echo = TRUE, eval = TRUE}
isp <- class_roll$email %>%
  strsplit("@", fixed = TRUE) %>%
  sapply("[", 2) %>%
  strsplit("[.]", fixed = FALSE) %>%
  sapply("[", 1)
tbl2 <- isp %>%
  `%in%`(c("naver", "gmail")) %>%
  ifelse(isp, "기타서비스") %>%
  factor(levels = c("naver", "gmail", "기타서비스"),
         labels = c("네이버", "구글", "기타서비스")) %>%
  table(class_roll$group, .) 
tbl2 %>%
  pander
X2min <- tbl2 %>%
  chisq.test(simulate.p.value = FALSE) %>%
  `[[`(1)
X2min
```

## 전화번호의 분포

```{r, cell_no, echo = TRUE, eval = TRUE}
cut_label <- paste(paste0(0:9, "000"), paste0(0:9, "999"), 
                   sep = "~")
tbl3 <- class_roll$cell_no %>%
  substr(start = 8, stop = 11) %>%
  sapply(as.numeric) %>%
  cut(labels = cut_label, 
      breaks = seq(0, 10000, by = 1000)) %>%
  table(class_roll$group, .) 
tbl3 %>%
  pander
X3min <- tbl3 %>%
  chisq.test(simulate.p.value = TRUE) %>%
  `[[`(1)
X3min
```

## 성씨 분포

```{r, name, echo = TRUE, eval = TRUE}
f_name <- class_roll$name %>%
  substring(first = 1, last = 1) 
tbl4 <- f_name %>%
  `%in%`(c("김", "이", "박", "최", "정")) %>%
  ifelse(f_name, "기타") %>%
  factor(levels = c("김", "이", "박", "최", "정", "기타")) %>%
  table(class_roll$group, .) 
tbl4 %>%
  pander
X4min <- tbl4 %>%
  chisq.test(simulate.p.value = TRUE) %>%
  `[[`(1)
X4min
```

## 단과대학

```{r, college, echo = TRUE, eval = TRUE}
tbl5 <- 
  class_roll %$%
  table(.$group, .$college) 
tbl5 %>%
  pander
X5min <- tbl5 %>%
  chisq.test(simulate.p.value = TRUE) %>%
  `[[`(1) 
X5min
```

### Sum of Chi_Squares

```{r, eval = TRUE}
Xsum_min <- X1min + X2min + X3min + X4min + X5min
Xsum_min
```
