theme_kr <-
structure(list(axis.title.x = structure(list(family = "HCR Dotum LVT", 
    face = NULL, colour = NULL, size = NULL, hjust = NULL, vjust = NULL, 
    angle = NULL, lineheight = NULL), .Names = c("family", "face", 
"colour", "size", "hjust", "vjust", "angle", "lineheight"), class = c("element_text", 
"element")), axis.title.y = structure(list(family = "HCR Dotum LVT", 
    face = NULL, colour = NULL, size = NULL, hjust = NULL, vjust = NULL, 
    angle = NULL, lineheight = NULL), .Names = c("family", "face", 
"colour", "size", "hjust", "vjust", "angle", "lineheight"), class = c("element_text", 
"element")), axis.text.x = structure(list(family = "HCR Dotum LVT", 
    face = NULL, colour = NULL, size = NULL, hjust = NULL, vjust = NULL, 
    angle = NULL, lineheight = NULL), .Names = c("family", "face", 
"colour", "size", "hjust", "vjust", "angle", "lineheight"), class = c("element_text", 
"element")), axis.text.y = structure(list(family = "HCR Dotum LVT", 
    face = NULL, colour = NULL, size = NULL, hjust = NULL, vjust = NULL, 
    angle = NULL, lineheight = NULL), .Names = c("family", "face", 
"colour", "size", "hjust", "vjust", "angle", "lineheight"), class = c("element_text", 
"element")), plot.title = structure(list(family = "HCR Dotum LVT", 
    face = NULL, colour = NULL, size = NULL, hjust = NULL, vjust = NULL, 
    angle = NULL, lineheight = NULL), .Names = c("family", "face", 
"colour", "size", "hjust", "vjust", "angle", "lineheight"), class = c("element_text", 
"element")), legend.title = structure(list(family = "HCR Dotum LVT", 
    face = NULL, colour = NULL, size = NULL, hjust = NULL, vjust = NULL, 
    angle = NULL, lineheight = NULL), .Names = c("family", "face", 
"colour", "size", "hjust", "vjust", "angle", "lineheight"), class = c("element_text", 
"element")), legend.text = structure(list(family = "HCR Dotum LVT", 
    face = NULL, colour = NULL, size = NULL, hjust = NULL, vjust = NULL, 
    angle = NULL, lineheight = NULL), .Names = c("family", "face", 
"colour", "size", "hjust", "vjust", "angle", "lineheight"), class = c("element_text", 
"element"))), .Names = c("axis.title.x", "axis.title.y", "axis.text.x", 
"axis.text.y", "plot.title", "legend.title", "legend.text"), class = c("theme", 
"gg"), complete = FALSE)
